---
title: "Tour d'horizon"
slug: "tour-d-horizon"
weight: 1
layout: "doc_BaRatinAGEPage"
inTOC: "BaRatinAGE"
---

# Généralités

BaRatinAGE v3 est un logiciel permettant d'estimer des courbes de tarage ainsi que leurs incertitudes, et de propager ces incertitudes aux hydrogrammes. La méthode BaRatin (*BAyesian RATINg curve*) est basée sur une [analyse hydraulique](/fr/doc/topics/analyse-hydraulique) de la station hydrométrique et sur l'[estimation bayésienne](/fr/doc/topics/bayesien) de la courbe de tarage. BaRatinAGE est l'acronyme de *BaRatin Advanced Graphical Environment*.

Pour installer BaRatinAGE v3, il vous suffit d'extraire le fichier zip que vous avez dû télécharger [ici](https://github.com/BaRatin-tools/BaRatinAGE/releases), **pourvu que vous ayez les droits d'écriture dans ce dossier**. Double-cliquez sur le fichier **BaRatinAGE.exe** (sous Linux : **bin/BaRatinAGE**), et (si tout va bien...) c'est parti!

Note : la langue par défaut au premier lancement de BaRatinAGE est le français. Vous pouvez changer la langue via le menu *Options...Changer de langue*.

# Principaux composants dans BaRatinAGE

BaRatinAGE manipule les composants suivants, dont le fonctionnement sera détaillé dans les pages qui suivent:

* La *configuration hydraulique* est la définition de l'ensemble des contrôles (hydrauliques) qui gouvernent la relation physique hauteur-débit, et de leur succession/combinaison lorsque la hauteur d'eau augmente. La configuration hydraulique induit l'équation qui sera utilisée pour la courbe de tarage.
* Le *jeu de jaugeages* est l'ensemble des mesures ponctuelles de hauteur et de débit qui seront utilisées pour estimer les paramètres de la courbe de tarage.
* Le *modèle d'erreur structurelle* définit les propriétés de l'erreur structurelle (ou "restante") de la courbe de tarage.
* La *courbe de tarage* est le modèle hauteur-débit estimé à partir d'une configuration hydraulique, d'un jeu de jaugeages et d'un modèle	d'erreur structurelle.
* Le *limnigramme* est la série temporelle de hauteur mesurée en continu au droit de la station hydrométrique.
* L'*hydrogramme* est la série temporelle de débit calculée à partir d'un limnigramme et d'une courbe de tarage.

Les quatre composants *configuration hydraulique*, *jeu de jaugeages*, *modèle d'erreur structurelle* et *limnigramme* sont des données d'entrée pour les calculs effectués par BaRatinAGE, et doivent donc être spécifiés par l'utilisateur. A l'opposé, les composants *courbe de tarage* et *hydrogramme* sont les résultats des calculs effectués par BaRatinAGE. Ils pourront être exportés sous différents formats.

