---
title: "Incertitudes sur les jaugeages"
slug: "jaugeages"
weight: 3
layout: "doc_topicsPage"
inTOC: "topics"
output:
  blogdown::html_page:
    number_sections: true
    toc: true
---

# Les jaugeages incertains comme données de calage

Pour l’analyse d’une courbe de tarage avec BaRatin, il faut fournir un ensemble de jaugeages représentatifs de la relation hauteur-débit pour la période considérée. La validité de ces jaugeages doit avoir été vérifiée (procédures qualité) au préalable, de façon à éviter les erreurs aberrantes, à assurer la continuité de leur raccordement à l’échelle de la station, et à maîtriser et documenter les erreurs de mesure. Il est notamment important de considérer :

* La technique de mesure et la procédure de jaugeage ;
* La date et les conditions hydrauliques au moment de la mesure, notamment : végétation, crue, détarage, etc. ;
* Le raccordement de la hauteur jaugée, surtout si l'échelle graduée de référence a connu des modifications ou un déplacement, ou si plusieurs échelles ont été utilisées simultanément. 

BaRatin permet la prise en compte d'incertitudes sur le débit et la hauteur jaugés, potentiellement différentes pour chaque jaugeage. Nous recommendons, au moins en première approche, d'ignorer les incertitudes sur les hauteurs jaugées et de plutot focaliser sur les incertitudes affectant les débits jaugés. Ces dernières permettent en particulier d'utiliser des jaugeages plus incertains (par exemple : jaugeages surfaciques, jaugeages anciens mal documentés) ou des estimations de débit (par exemple : enquête après crue) dans des gammes peu ou pas jaugées, en pondérant leur contribution. Il est capital de spécifier pour les jaugeages des valeurs d'incertitude réalistes, ni sous-estimées ni surestimées, car elles impactent à la fois le tracé de la courbe et la largeur de son faisceau d'incertitude.

BaRatin fait l’hypothèse (forte) que les erreurs de mesure sont indépendantes d’un jaugeage à l’autre. Cette hypothèse est manifestement violée si l’on fournit à BaRatin des jaugeages effectués en conditions de répétabilité, typiquement avec le même instrument, au même endroit, le même jour, dans les mêmes conditions hydrauliques, etc. Ceci peut conduire à une sous-estimation de l’incertitude de la courbe de tarage. Il faut donc éviter d’inclure des jaugeages répétés (par exemple
des jaugeages ADCP successifs pour un débit équivalent), mais soit les sous-échantillonner, soit les moyenner ensemble.

> Attention : Dans BaRatinAGE, l’incertitude des jaugeages est exprimée comme la demi-longueur d'un intervalle d'incertitude au niveau de confiance de 95 %, soit 1.96 écarts-types sous hypothèse de distribution gaussienne des erreurs, en valeur relative (en %) pour le débit jaugé et en mètres pour la hauteur jaugée.

# Incertitude des débits jaugés

L'incertitude sur le débit jaugé peut être estimée à partir des informations disponibles sur les mesures de débit, ou calculée par des méthodes de propagation des incertitudes. Pour les jaugeages par exploration du champ des vitesses, le calcul des incertitudes peut être fait avec la méthode de la norme ISO748, la méthode IVE de l’USGS, la méthode Q+ implémentée dans le logiciel BAREME, ou encore la méthode FLAURE. Toutes ces méthodes ont des limitations. Il est possible d'exporter depuis BAREME vers BaRatin une sélection de jaugeages munis d'une incertitude calculée par la méthode Q+ ou estimée par une autre méthode.

Selon la technique employée et les conditions de mesure, l'incertitude individuelle des jaugeages peut être évaluée simplement selon des calculs simplifiés [Le Coz et al., 2011](www.onema.fr/IMG/pdf/controle-debits-reglementaires-2.pdf). Les comparaisons inter-laboratoire permettent également de déterminer empiriquement l'incertitude d’une technique de jaugeage déployée dans les conditions de mesure des essais. Cette incertitude est typiquement prise égale à ±7% pour les débits jaugés au moulinet/courantomètre avec au moins une dizaine de verticales décrivant correctement l’écoulement, et à ±5% pour un jaugeage par ADCP réalisé dans de bonnes conditions (±10% en mauvaises conditions). 

La liste suivante propose des valeurs d’incertitude (élargies à 95%) typiques sur le débit pour les principales techniques de jaugeage. **Attention, ces valeurs d’incertitude typiques ne sont fournies qu’à titre d’exemple. Une analyse des incertitudes des jaugeages au cas par cas, au moins par catégories, est fortement recommandée**.

* **Volumétrie** : de ±5\% (conditions optimales) à ±10\% (conditions dégradées)
* **Exploration du champ des vitesses**
    * **ADCP** : de ±5\% à ±10\% 
    * **Moulinet ou courantomètre** : de ±7\% à ±15\%
    * **Flotteurs** : de ±10\% à ±50\%
    * **Radar ou LSPIV** : de ±10\% à ±20\%
* **Dilution de traceur** : de ±3\% à ±10\%
* **Formules hydrauliques** : de ±5\% à ±40\%

# Incertitude des hauteurs jaugées

Outre l’incertitude des débits jaugés, BaRatinAGE permet aussi de prendre en compte l’incertitude des hauteurs jaugées. Cependant, en première approche et en routine, il est recommandé de l’ignorer, en la spécifiant égale à zéro pour tous les jaugeages. En effet, prendre en compte cette incertitude augmente sensiblement la complexité et la durée des calculs puisque l’erreur de hauteur de chaque jaugeage devient un paramètre supplémentaire à estimer, en plus de ceux de la courbe de tarage et de l’incertitude restante. Et les résultats sont en général très peu différents, sauf si l’incertitude de hauteur de jaugeages importants pour le calage est forte. 

Contrairement à l’incertitude des débits, cette incertitude sur les hauteurs n’est jamais exprimée en valeur relative (en %) mais toujours en mètres. Les principales sources d’erreur sur la hauteur jaugée incluent : la lecture de l’échelle, sa résolution, le batillage, la déformation de la surface libre à proximité de l’échelle, le raccordement du jaugeage lorsqu’il a été mesuré avec une autre échelle, le décalage temporel si la lecture d’échelle n’est pas faite pendant le jaugeage, et surtout la variation du niveau d’eau pendant les opérations de jaugeage, en particulier en situation de crue ou de décrue. Cette dernière composante d’incertitude peut s’estimer simplement ainsi (incertitude élargie à 95%) :

$$U=\frac{h_{max}-h_{min}}{sqrt(3)}$$

avec $h_{max}$ et $h_{min}$ les hauteurs maximum et minimum atteintes en cours de jaugeage. Ces différentes sources d’erreurs étant supposées indépendantes, l’incertitude combinée s’obtient par somme quadratique de toutes les incertitudes élémentaires.


