---
title: "Friction coefficients"
slug: "friction-coefficients"
weight: 21
layout: "doc_topicsPage"
inTOC: "topics"
output:
  blogdown::html_page:
    number_sections: true
    toc: true
---

# Introduction

The flow resistance parameters (or flow friction factors)  of channel controls are often difficult to determine precisely.
In engineering practice, they are often expressed as Strickler coefficient $K_S$ or Manning coefficient $n$, one being the opposite of the other ($n=1/K_S$).
There exist look-up tables of typical values (e.g., [Chow's table](Chow_en.xlsx), or this [illustrated catalogue](https://wwwrcamnl.wr.usgs.gov/sws/fieldmethods/Indirects/nvalues/ index.htm)) and calculation methods based on a more detailed description of flow conditions (e.g., [Cowan method](Cowan_en.xlsx), or the method of [Arcement and Schneider, 1989](https://pubs.usgs.gov/publication/wsp2339)).

Other interesting references on friction factor estimation:

* Barnes, H.H. (1967) Roughness characteristics of natural channels. U.S. Geological Survey Water-Supply Paper 1849, 213.
* Hey, R.D. (1979) Flow resistance in gravel-bed rivers. J. Hydraul. Div., Am. Soc. Civ. Eng., 105(4), 365–379.
* Hicks, D.M., Mason, P.D. (1998) Roughness Characteristics of New Zealand Rivers, Water Resources Publications, Littleton, CO, 329 pp., ISBN:0-477-02608-7.
* Jarrett, R.D. (1985) Determination of roughness coefficients for streams in Colorado. U.S. Geological Survey Water-Resources Investigations Rep. 85-4004, 54.
* Limerinos, J.T. (1970) Determination of the Manning coefficient from measured bed roughness in natural channels. U.S. Geological Survey Water Supply Paper 1898-B, 47.



# Chow Table, 1959 (Strickler)


The following table gives the values of Strickler coefficient in m$^{1/3}$/s, for given channel types, and for minimum, ‘normal’ and maximum friction.

Source: Ven Te Chow (1959). Open-Channel Hydraulics. McGraw-Hill, New York.


| Type of channel and description          | Minimum | Normal  | Maximum |
|:---------------------------------------|:--------|:--------|:--------|
| **1. Main channels, natural watercourses - minor streams (full width < 30 m / 100 ft)** ||||
|                       a. clean, straight, full stage, no rifts or deep pools | 40 | 33 | 30 |
|                       b. same as above, but with more stones and weeds | 33 | 29 | 25 |
|                       c. clean, winding, some pools and shoals | 30 | 25 | 22 |
|                       d. same as above, but with some weeds and stones | 29 |    22 |	20 |
|                       e. same as above, lower stages, more ineffective slopes and sections |    25 |    21 |    18 |
|                       f. same as ‘d’ with more stones |    22 |    20 |	17 |
|                       g. sluggish reaches, weedy, deep pools |    20 |    14 |    13 |
|                       h. very weedy reaches, deep pools, or floodwayswith heavy stand of timber and underbrush |    13 |    10 |    7 |
|     **2. Mountain streams, no vegetation in channel, banks usually steep, trees and brush along banks submerged at high stages**     |          |          |          | 
|                           a. bottom: gravels, cobbles, and a few boulders     |     33     |     25     |     20     |
|                           b. bottom: cobbles with large boulders     |     25     |     20     |     14     | 
|     **3. Floodplains**     |          |          |          | 
|                           a. pasture, no brush     |          |          |          | 
|                                             1. short grass     |     40     |     33     |     29     | 
|                                             2. high grass     |     33     |     29     |     20     | 
|                           b. cultivated areas     |          |          |          | 
|                                             1. no crop     |     50     |     33     |     25     | 
|                                             2. mature row crops      |     40     |     29     |     22     | 
|                                             3. mature field crops     |     33     |     25     |     20	 | 
|                           c. brush     |          |          |          | 
|                                             1. scattered brush, heavy weeds     |     29     |     20     |     14     | 
|                                             2. light brush and trees, in winter     |     29	 |     20     |     17     | 
|                                             3. light brush and trees, in summer     |     25     |     17     |     13     | 
|                                             4. medium to dense brush, in winter     |     22     |     14     |     9     | 
|                                             5. medium to dense brush, in summer     |     14     |     10     |     6     | 
|                           d. trees     |          |          |          | 
|                                             1. dense willows, summer, straight     |     9     |     7     |     5     | 
|                                             2. cleared land with tree stumps, no sprouts     |     33     |     25     |     20     | 
|                                             3. same as above, but with heavy growth of sprouts     |     20     |     17     |     13     | 
|                                             4. heavy stand of timber, a few down trees, little undergrowth, flood stage below branches      |     20     |     21     |     22     | 
|                                             5. same as 4. with flood stage reaching  branches     |     10     | 	8     |     6     | 
|     **4. Excavated or dredged channels**     |          |          |          | 
|                           a. earth, straight, and uniform     |          |          |          | 
|                                             1. clean, recently completed     |     63     |     56	 |     50     | 
|                                             2. clean, after weathering     |     56     |     45     |     40     | 
|                                             3. gravel, uniform section, clean     |     45     |     40     |     33     | 
|                                             4. with short grass, few weeds     |     45     |     37     |     30     | 
|                           b. earth, winding, and sluggish     |          |          |          | 
|                                             1. no vegetation     |     43     |     40     |     33	 | 
|                                             2. grass, some weeds     |     40     |     33     |     30     | 
|                                             3. dense weeds or aquatic plants in deep channels     |     33     |     29     |     25	 | 
|                                             4. earth bottom and rubble sides     |     36     |     33     |     29     | 
|                                             5. stony bottom and weedy banks     |     40     |     29     |     25     | 
|                                             6. cobble bottom and clean sides     |     33	 |     25     |     20     | 
|                           c. dragline-excavated or dredged     |          |          |          | 
|                                             1. no vegetation     |     40     |     36     |     30     | 
|                                             2. light brush on banks     |     29     |     20     |     17     | 
|                           d. rock cuts     |          |          |          | 
|                                             1. smooth and uniform     |     40     |     29     |     25	 | 
|                                             2. jagged and irregular     |     29     |     25     |     20     | 
|                           e. channels not maintained, weeds and brush uncut     |          |          |          | 
|                                             1. dense weeds, high as flow depth     |     20     |     13     |     8     | 
|                                             2. clean bottom, brush on sides     |     25     |     20     |     13	 | 
|                                             3. same as above, highest stage of flow     |     22     |     14     |     9     | 
|                                             4. dense brush, high stage     |     13     |     10     |     7	 | 
|     **5. Lined or constructed channels**     |          |          |          | 
|                           a. cement     |          |          |          | 
|                                             1. neat surface     |     100     |     91     |     77	 | 
|                                             2. mortar     |     91     |     77     |     67     | 
|                           b. wood     |          |          |          | 
|                                             1. planed, untreated     |     100     |     83     |     71	 | 
|                                             2. planed, creosoted     |     91     |     83     |     67     | 
|                                             3. unplaned     |     91     |     77     |     67     | 
|                                             4. plank with battens     |     83     |     67     |     56	 | 
|                                             5. lined with roofing paper     |     100     |     71     |     59     | 
|                           c. concrete     |          |          |          | 
|                                             1. trowel finish     |     91     |     77     |     67     |
|                                             2. float finish     |     77     |     67     |     63     | 
|                                             3. finished, with gravel on bottom     |     67     |     59     |     50     | 
|                                             4. unfinished     |     71     |     59	 |     50     | 
|                                             5. gunite, good section     |     63     |     53     |     43     | 
|                                             6. gunite, wavy section     |     56     |     45     |     40     | 
|                                             7. on good excavated rock     |     59	 |     50     |          | 
|                                             8. on irregular excavated rock     |     45     |     37     |          | 
|                           d. concrete bottom float finish with sides of:     |          |          |          | 
|                                             1. dressed stone in mortar     |     67     |     59     |     50     | 
|                                             2. random stone in mortar     |     59     |     50     |     42     | 
|                                             3. cement rubble masonry, plastered     |     63     |     50     |     42	 | 
|                                             4. cement rubble masonry     |     50     |     40     |     33     | 
|                                             5. dry rubble or riprap     |     50     |     33     |     29     | 
|                           e. gravel bottom with sides of:     |          |          |          | 
|                                             1. formed concrete     |     59     |     50     |     40     | 
|                                             2. random stone mortar     |     50     |     43     |     38     | 
|                                             3. dry rubble or riprap     |     43     |     30     |     28     | 
|                           f. brick     |          |          |          | 
|                                             1. glazed     |     91     |     77     |     67     | 
|                                             2. in cement mortar     |     83     |     67     |     56     | 
|                           g. masonry     |          |          |          | 
|                                             1. cemented rubble     |     59     |     40     |     33	 |
|                                             2. dry rubble     |     43     |     31     |     29     | 
|                           h. dressed ashlar/stone paving     |     77     |     67     |     59     | 
|                           i. asphalt     |          |          |          | 
|                                             1. smooth     |     77     |     77     |          | 
|                                             2. rough     |     63     |     63     |          | 
|                           j. Vegetal lining     |     33     |          |     2     | 



# Chow table, 1959 (Manning)


The following table gives the values of the Manning coefficient in s/m$^{1/3}$, for given channel types, and for minimum, ‘normal’ and maximum friction.

Source: Ven Te Chow (1959). Open-Channel Hydraulics. McGraw-Hill, New York.


**TEXTS TO BE FIXED AS DONE ABOVE FOR STRICKLER TABLE**


| Channel type and description          | Minimum | Normal  | Maximum |
|:---------------------------------------|:--------|:--------|:--------|
| **1. Main channels, natural watercourses - minor streams (full width < 30 m / 100 ft)** ||||
|            a. clean, straight, full stage, no rifts or deep pools | 0.025  | 0.030 | 0.033 |
|            b. same as above, but with more stones and weeds | 0.030 | 0.035 | 0.040 |
|            c. clean, winding, some pools and shoals | 0.033 | 0.040 | 0.045 |
|            d. same as above, but with some weeds and stones | 0.035 |    0.045 |    0.050 |
|            e. same as above, lower stages, more ineffective slopes and sections |    0.040 |    0.048 |    0.055 |
|            f. same as ‘d’ with more stones |    0.045 |    0.050 |    0.060 |
|            g. sluggish reaches, weedy, deep pools |    0.050 |    0.070 |    0.080 |
|            h. very weedy reaches, deep pools, or floodwayswith heavy stand of timber and underbrush |    0.075 |    0.100 |    0.150 |
|     **2. Mountain streams, no vegetation in channel, banks usually steep, trees and brush along banks submerged at high stages**     |          |          |          | 
|                a. bottom: gravel, cobbles, and a few boulders     |     0.030     |     0.040     |     0.050     | 
|                b. bottom: cobbles with large boulders     |     0.040     |     0.050     |     0.070	 | 
|     **3. Floodplains**     |          |          |          | 
|                a. Pasture, no brushb     |          |          |          | 
|                         1. Short grass     |     0.025      |     0.030     |     0.035	 | 
|                         2. High grass     |     0.030     |     0.035     |     0.050     | 
|                b. Cultivated areas     |          |          |          | 
|                         1. No crop     |     0.020     |     0.030	 |     0.040     | 
|                         2. Mature row crops      |     0.025      |     0.035     |     0.045     | 
|                         3. Mature field crops      |     0.030     |     0.040     |     0.050	 | 
|                c. Brush     |          |          |          | 
|                         1. Scattered brush, heavy weeds     |     0.035     |     0.050 |     0.070     | 
|                         2. Light brush and trees, in winter     |     0.035     |     0.050     |     0.060     | 
|                         3. Light brush and trees, in summer     |     0.040     |     0.060     |     0.080	 | 
|                         4. Medium to dense brush, in winter     |     0.045     |     0.070     |  0.110     | 
|                         5. Medium to dense brush, in summer     |     0.070     |     0.100     |     0.160	 | 
|                d. Trees     |          |          |          | 
|                         1. Dense willows, in summer, straight     |     0.110     |     0.150     |     0.020	 | 
|                         2. Cleared land with tree stumps, no sprouts     |     0.030     |     0.040     |     0.050     | 
|                         3. Same as above, but with heavy growth of sprouts     |     0.050     |     0.060	 |     0.080     | 
|                         4. Heavy stand of timber, a few down trees, little undergrowth, flood stage below branches      |     0.050     |     0.048     |     0.045     | 
|                         5. Same as 4. with flood stage reaching  branches     |     0.100     |     0.120     | 0.160     | 
|     **4. Excavated or dredged channels**     |          |          |          | 
|                a. earth, straight, and uniform     |          |          |          | 
|                         1. Clean, recently completed     |     0.016     |     0.018     |     0.020     | 
|                         2. Clean, after weathering     |     0.018	 |     0.022     |     0.025                         | 
|                         3. Gravel, uniform section, clean     |     0.022     |     0.025      |     0.030     | 
|                         4. with short grass, few weeds     |     0.022     |     0.027     |     0.033     | 
|                b. earth, winding, and sluggish     |          |          |          | 
|                         1. no vegetation     |     0.023     |     0.025      |     0.030     | 
|                         2. grass, some weeds     |     0.025     |     0.030     |     0.033	 | 
|                         3. dense weeds or aquatic plants in deep channels     |     0.030     |     0.035     |     0.040     | 
|                         4. earth bottom and rubble sides     |     0.028     |     0.030     |     0.035	 | 
|                         5. stony bottom and weedy banks     |     0.025     |     0.035     |     0.040     | 
|                         6. cobble bottom and clean sides     |     0.030     |     0.040     |     0.050	 | 
|                c. dragline-excavated or dredged     |          |          |          | 
|                         1. No vegetation     |     0.025     |     0.028     |     0.033     | 
|                         2. light brush on banks     |     0.035	 |     0.050     |     0.060     | 
|                d. Rock cuts     |          |          |          | 
|                         1. smooth and uniform     |     0.025     |     0.035     |     0.040	 | 
|                         2. jagged and irregular     |     0.035     |     0.040     |     0.050     | 
|                e. channels not maintained, weeds and brush uncut     |          |          |          | 
|                         1. dense weeds, high as flow depth     |     0.050     |     0.080     |     0.120     | 
|                         2. Clean bottom, brush on sides     |     0.040     |     0.050     |     0.080     | 
|                         3. same as above, highest stage of flow     |     0.045     |     0.070     |     0.110     | 
|                         4. dense brush, high stage     |     0.080     |     0.100     |     0.150	 | 
|     **5. Lined or constructed channels**     |          |          |          | 
|                a. Cement     |          |          |          | 
|                         1. Neat surface     |     0.010     |     0.011     |     0.013	 | 
|                         2. Mortar     |     0.110     |     0.013     |     0.015     | 
|                b. Wood     |          |          |          | 
|                         1. Planed, untreated     |     0.010     |     0.012	 |     0.014     | 
|                         2. planed, creosoted     |     0.110     |     0.012     |     0.015     | 
|                         3. unplaned     |     0.110     |     0.013     |     0.015	 | 
|                         4. plank with battens     |     0.012     |     0.015     |     0.018     | 
|                         5. lined with roofing paper     |     0.010     |     0.014     |     0.017	 | 
|                c. Concrete     |          |          |          | 
|                         1. Trowel finish     |     0.110     |     0.013     |     0.015	 | 
|                         2. Float finish     |     0.013     |     0.015     |     0.016     | 
|                         3. finished, with gravel on bottom     |     0.015     |     0.017     |     0.020	 | 
|                         4. unfinished     |     0.014     |     0.017     |     0.020     | 
|                         5. gunite, good section     |     0.016     |     0.019     |     0.023	 | 
|                         6. Gunite, wavy section     |     0.018     |     0.022     |     0.025     | 
|                         7. on good excavated rock     |     0.017     |     0.020     |          | 
|                         8. on irregular excavated rock     |     0.022     |     0.027     |          | 
|                d. concrete bottom float finish with sides of:     |          |          |          | 
|                         1. dressed stone in mortar     |     0.015     |     0.017     |     0.020	 | 
|                         2. random stone in mortar     |     0.017     |     0.020     |     0.024     | 
|                         3. cement rubble masonry, plastered     |     0.016     |     0.020     |     0.024	 | 
|                         4. cement rubble masonry     |     0.020     |     0.025     |     0.030     | 
|                         5. dry rubble or riprap     |     0.020     |     0.030     |     0.035	 | 
|                e. gravel bottom with sides of:     |          |          |          | 
|                         1. Formed concrete     |     0.017     |     0.020     |     0.025	 | 
|                         2. Random stone mortar     |     0.020     |     0.023     |     0.026     | 
|                         3. dry rubble or riprap     |     0.023     |     0.033     |     0.036	 | 
|                f. Brick     |          |          |          | 
|                         1. Glazed     |     0.110     |     0.013     |     0.015	 | 
|                         2. in cement mortar     |     0.012     |     0.015     |     0.018     | 
|                g. Masonry     |          |          |          | 
|                         1. cemented rubble     |     0.017     |     0.025     |     0.030     | 
|                         2. dry rubble     |     0.023     |     0.032     |     0.035     | 
|                h. dressed ashlar/stone paving     |     0.013     |     0.015     |     0.017     | 
|                i. Asphalt     |          |          |          | 
|                         1. Smooth     |     0.013     |     0.013     |          | 
|                         2. rough     |     0.016     |     0.016     |          | 
|                j. Vegetation lining     |     0.030     |          |     0.500     | 
